/**
 * mapeditor/render-gallery.cjs — render every map as an SVG thumbnail plus a
 * MAPS.md index, so maps are viewable directly in the GitHub repo UI
 * (GitHub renders .svg images and .md files natively).
 *
 *   node mapeditor/seed.cjs          # first (builds maps/curated.json)
 *   node mapeditor/render-gallery.cjs
 *
 * Writes mapeditor/gallery/<name>.svg for each map and
 * mapeditor/gallery/MAPS.md as the index. Runs automatically in CI via
 * .github/workflows/map-gallery.yml.
 */
'use strict';

const fs = require('fs');
const path = require('path');
const MapCore = require('./mapcore.cjs');

const ROOT = path.join(__dirname, '..');
const OUT_DIR = __dirname;

const maps = [];

// Curated maps (generated by seed.cjs from src/data/maps.ts).
try {
	const curated = JSON.parse(fs.readFileSync(path.join(ROOT, 'maps', 'curated.json'), 'utf8'));
	for (const c of (curated.maps || [])) {
		maps.push({ name: c.name, display: c.displayName || c.name, rows: c.rows, cols: c.cols, tiles: c.tiles, source: 'curated' });
	}
} catch (e) {
	console.error('Could not read maps/curated.json — run `node mapeditor/seed.cjs` first.');
	process.exit(1);
}

// Volunteer maps (maps/*.txt).
const mapsDir = path.join(ROOT, 'maps');
if (fs.existsSync(mapsDir)) {
	for (const f of fs.readdirSync(mapsDir).filter((x) => x.endsWith('.txt')).sort()) {
		try {
			const m = MapCore.parseTxt(fs.readFileSync(path.join(mapsDir, f), 'utf8'), f);
			maps.push({ name: m.name, display: m.displayName, rows: m.rows, cols: m.cols, tiles: m.tiles, source: 'volunteer' });
		} catch (e) {
			console.error('  ! ' + e.message);
		}
	}
}

maps.sort((a, b) => a.name.localeCompare(b.name));

const galleryDir = path.join(OUT_DIR, 'gallery');
if (!fs.existsSync(galleryDir)) fs.mkdirSync(galleryDir, { recursive: true });

const esc = (s) => String(s).replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;').replace(/"/g, '&quot;');

const CELL = 16;
const PAD = 14;
const TITLE_H = 20;

function svgFor(map) {
	const w = PAD * 2 + map.cols * CELL;
	const h = PAD + TITLE_H + map.rows * CELL + PAD;
	let out = '<svg xmlns="http://www.w3.org/2000/svg" width="' + w + '" height="' + h + '" viewBox="0 0 ' + w + ' ' + h + '">\n';
	out += '<rect width="100%" height="100%" fill="#0d1117"/>\n';
	out += '<text x="' + PAD + '" y="' + (PAD + 4) + '" fill="#8b97b3" font-family="ui-monospace,Menlo,Consolas,monospace" font-size="11">' + esc(map.name) + ' · ' + map.rows + '×' + map.cols + '</text>\n';
	for (let r = 0; r < map.rows; r++) {
		for (let c = 0; c < map.cols; c++) {
			const t = MapCore.TERRAINS[map.tiles[r][c]] || MapCore.TERRAINS.normal;
			const x = PAD + c * CELL;
			const y = PAD + TITLE_H + r * CELL;
			out += '<rect x="' + x + '" y="' + y + '" width="' + CELL + '" height="' + CELL + '" fill="' + t.color + '" stroke="#000" stroke-width="0.5"/>\n';
		}
	}
	out += '</svg>\n';
	return out;
}

const bySize = {};
for (const m of maps) {
	fs.writeFileSync(path.join(galleryDir, m.name + '.svg'), svgFor(m), 'utf8');
	const k = m.rows + '×' + m.cols;
	(bySize[k] = bySize[k] || []).push(m);
}

// MAPS.md — index grouped by size, 4 previews per row.
let md = '# Battle Dome map gallery\n\n';
md += 'Auto-generated by the **Map gallery** GitHub Action from `src/data/maps.ts` (curated) and `maps/*.txt` (volunteer).\n';
md += 'Push changes to those files and this page regenerates itself. For an interactive view, use the [map editor](https://4-mat.github.io/bd-autohost-bot-new/mapeditor/).\n\n';
md += '**' + maps.length + ' maps**\n\n';

const sizeRank = (k) => {
	const [r, c] = k.split('×').map(Number);
	return r * 1000 + c;
};
const sizes = Object.keys(bySize).sort((a, b) => sizeRank(a) - sizeRank(b));

for (const k of sizes) {
	const list = bySize[k];
	md += '## ' + k + ' (' + list.length + ')\n\n';
	for (let i = 0; i < list.length; i += 4) {
		const row = list.slice(i, i + 4);
		md += '| ' + row.map(() => '').join(' | ') + ' |\n';
		md += '| ' + row.map(() => '---').join(' | ') + ' |\n';
		md += '| ' + row.map((m) => '<img src="./' + m.name + '.svg" width="128" alt="' + esc(m.name) + '"><br>[' + esc(m.name) + '](./' + m.name + '.svg)').join(' | ') + ' |\n\n';
	}
}

fs.writeFileSync(path.join(galleryDir, 'MAPS.md'), md, 'utf8');
console.log('wrote ' + maps.length + ' SVG(s) + MAPS.md → mapeditor/gallery/');
