services:
  - type: web
    name: bd-autohost-test
    env: node
    plan: free
    buildCommand: npm install && npm run build
    startCommand: node dist/test-app.js
    envVars:
      - key: NODE_VERSION
        value: 20.14.0
