// scripts/apply-editor-proposal.ts
//
// Applies a public Ability Editor proposal (from an "Ability: ..." issue) to
// src/data/index.ts. Runs in CI inside .github/workflows/ability-pr.yml:
//
//   bun scripts/apply-editor-proposal.ts <proposal.json>
//
// The payload (generated by the demo's "Propose to Bot") looks like:
//
//   {
//     "updates": [{ "kind": "class", "name": "Bard", "entry": { ...full entry... } }],
//     "adds":    [{ "kind": "weapon", "entry": { ...full new entry... } }]
//   }
//
// Entries are sanitized (normalizeProposalEntry) and applied via the shared
// serializer, which rewrites only the changed blocks (minimal diff). Prints a
// one-line summary on success; exits non-zero with a reason on rejection.

import fs from "fs";
import path from "path";
import { fileURLToPath } from "url";
import {
  readSourceText,
  writeSourceText,
  regenerateSourceText,
  normalizeProposalEntry,
  findBlocks,
  type EntryType,
} from "../abilityeditor/serializer.js";

const ROOT = path.join(path.dirname(fileURLToPath(import.meta.url)), "..");
const SRC_PATH = path.join(ROOT, "src", "data", "index.ts");

interface ProposalOp {
  kind?: unknown;
  name?: unknown;
  entry?: unknown;
}

interface Proposal {
  updates?: ProposalOp[];
  adds?: ProposalOp[];
}

function fail(msg: string): never {
  console.error("PROPOSAL REJECTED: " + msg);
  process.exit(1);
}

function typeOf(kind: unknown, ctx: string): EntryType {
  if (kind === "class") return "ClassData";
  if (kind === "weapon") return "WeaponData";
  fail(ctx + " has invalid kind (use class or weapon)");
}

function asRecord(v: unknown): Record<string, unknown> {
  return v && typeof v === "object" && !Array.isArray(v)
    ? (v as Record<string, unknown>)
    : {};
}

function main(): void {
  const arg = process.argv[2];
  if (!arg) fail("usage: bun scripts/apply-editor-proposal.ts <proposal.json>");

  let raw: Proposal;
  try {
    raw = JSON.parse(fs.readFileSync(arg, "utf8")) as Proposal;
  } catch (e) {
    fail("could not parse proposal payload: " + (e as Error).message);
  }
  if (!raw || !Array.isArray(raw.updates) || !Array.isArray(raw.adds)) {
    fail("payload must contain updates[] and adds[] arrays");
  }

  const text = readSourceText(SRC_PATH);
  const existing = new Set(findBlocks(text).map((b) => b.name));
  // Names already claimed: existing source entries + anything accepted earlier
  // in this payload. Guards against duplicate adds, duplicate updates, and
  // update/add collisions, which would otherwise produce broken output.
  const seen = new Set(existing);

  const entries: { name: string; type: EntryType; entry: Record<string, unknown> }[] = [];

  for (const u of raw.updates) {
    const type = typeOf(u.kind, "an update");
    const name = String(u.name ?? "").trim();
    if (!name) fail("an update is missing a name");
    if (seen.has(name)) {
      fail("duplicate name '" + name + "' in the proposal — each entry may appear once");
    }
    const entry = normalizeProposalEntry(asRecord(u.entry), type);
    if (entry.name !== name) {
      fail(
        "update name mismatch: payload says '" + name + "' but the entry is named '" + entry.name + "'",
      );
    }
    if (!existing.has(name)) {
      fail("update targets '" + name + "' which does not exist in src/data/index.ts");
    }
    seen.add(name);
    entries.push({ name, type, entry });
  }

  for (const a of raw.adds) {
    const type = typeOf(a.kind, "an add");
    const entry = normalizeProposalEntry(asRecord(a.entry), type);
    if (!entry.name) fail("an add is missing a name");
    if (seen.has(entry.name)) {
      if (existing.has(entry.name)) {
        fail(
          "add '" + entry.name + "' already exists in src/data/index.ts — propose an edit instead",
        );
      }
      fail("duplicate name '" + entry.name + "' in the proposal — each entry may appear once");
    }
    seen.add(entry.name);
    entries.push({ name: entry.name, type, entry });
  }

  if (entries.length === 0) fail("no changes to apply");

  const result = regenerateSourceText(text, entries);
  if (result.changed.length === 0 && result.inserted.length === 0) {
    console.log("no changes needed — the data already matches");
    return;
  }

  writeSourceText(SRC_PATH, result.out);

  const parts: string[] = [];
  if (result.changed.length) {
    parts.push("updated " + result.changed.length + ": " + result.changed.join(", "));
  }
  if (result.inserted.length) {
    parts.push("added " + result.inserted.length + ": " + result.inserted.join(", "));
  }
  console.log(parts.join("; "));
}

main();
