// scripts/apply-editor-proposal.ts
//
// Applies a public Ability Editor proposal (from an "Ability: ..." issue) to
// src/data/index.ts. Runs in CI inside .github/workflows/ability-pr.yml:
//
//   bun scripts/apply-editor-proposal.ts <proposal.json>
//
// The payload (generated by the demo's "Propose to Bot") looks like:
//
//   {
//     "updates": [{ "kind": "class", "name": "Bard", "entry": { ...full entry... } }],
//     "adds":    [{ "kind": "weapon", "entry": { ...full new entry... } }]
//   }
//
// Entries are sanitized (normalizeProposalEntry) and applied via the shared
// serializer, which rewrites only the changed blocks (minimal diff). Prints a
// one-line summary on success; exits non-zero with a reason on rejection.
// The core logic is exported for unit tests
// (src/__tests__/apply-editor-proposal.test.ts).

import fs from "fs";
import path from "path";
import { fileURLToPath, pathToFileURL } from "url";
import {
  readSourceText,
  writeSourceText,
  regenerateSourceText,
  normalizeProposalEntry,
  findBlocks,
  toId,
  type EntryLike,
  type EntryType,
  type RegenResult,
} from "../abilityeditor/serializer.js";

const ROOT = path.join(path.dirname(fileURLToPath(import.meta.url)), "..");
const SRC_PATH = path.join(ROOT, "src", "data", "index.ts");

export interface ProposalOp {
  kind?: unknown;
  name?: unknown;
  entry?: unknown;
}

export interface Proposal {
  updates?: ProposalOp[];
  adds?: ProposalOp[];
}

function typeOf(kind: unknown, ctx: string): EntryType {
  if (kind === "class") return "ClassData";
  if (kind === "weapon") return "WeaponData";
  throw new Error(ctx + " has invalid kind (use class or weapon)");
}

function asRecord(v: unknown): Record<string, unknown> {
  return v && typeof v === "object" && !Array.isArray(v)
    ? (v as Record<string, unknown>)
    : {};
}

/**
 * Validate a proposal and produce the regenerated source text. Pure — no file
 * I/O, so it is unit-testable. Throws an Error on any validation failure.
 */
export function applyProposalText(text: string, raw: Proposal): RegenResult {
  if (!raw || !Array.isArray(raw.updates) || !Array.isArray(raw.adds)) {
    throw new Error("payload must contain updates[] and adds[] arrays");
  }

  // Bounded public surface: the workflow runs on any "Ability: ..." issue.
  const rawSize = JSON.stringify(raw).length;
  if (rawSize > 100_000) {
    throw new Error("proposal payload too large — " + rawSize + " bytes (max 100 KB)");
  }
  if (raw.updates.length + raw.adds.length > 100) {
    throw new Error("too many entries in the proposal (max 100)");
  }

  const existing = new Set(findBlocks(text).map((b) => b.name));
  // Case-insensitive (toId) membership: catches duplicates like "Foo"/"foo"
  // and adds colliding with an existing entry regardless of case. Existing
  // name targeting stays exact, matching regenerateSourceText's block lookup.
  const existingIds = new Set([...existing].map(toId));
  const seen = new Set<string>(); // toId of names accepted earlier in this payload

  const entries: EntryLike[] = [];

  for (const u of raw.updates) {
    const type = typeOf(u.kind, "an update");
    const name = String(u.name ?? "").trim();
    if (!name) throw new Error("an update is missing a name");
    if (seen.has(toId(name))) {
      throw new Error(
        "duplicate name '" + name + "' in the proposal — each entry may appear once",
      );
    }
    const entry = normalizeProposalEntry(asRecord(u.entry), type);
    if (entry.name !== name) {
      throw new Error(
        "update name mismatch: payload says '" +
          name +
          "' but the entry is named '" +
          entry.name +
          "'",
      );
    }
    if (!existing.has(name)) {
      throw new Error("update targets '" + name + "' which does not exist in src/data/index.ts");
    }
    seen.add(toId(name));
    entries.push({ name, type, entry });
  }

  for (const a of raw.adds) {
    const type = typeOf(a.kind, "an add");
    const entry = normalizeProposalEntry(asRecord(a.entry), type);
    if (!entry.name) throw new Error("an add is missing a name");
    const id = toId(entry.name);
    if (seen.has(id)) {
      throw new Error(
        "duplicate name '" + entry.name + "' in the proposal — each entry may appear once",
      );
    }
    if (existingIds.has(id)) {
      throw new Error(
        "add '" + entry.name + "' already exists in src/data/index.ts — propose an edit instead",
      );
    }
    seen.add(id);
    entries.push({ name: entry.name, type, entry });
  }

  if (entries.length === 0) throw new Error("no changes to apply");

  return regenerateSourceText(text, entries);
}

/**
 * Read a proposal file and apply it to srcPath, writing only when something
 * actually changed. Returns the changed/inserted names.
 */
export function applyProposalFile(
  proposalPath: string,
  srcPath: string,
): { changed: string[]; inserted: string[] } {
  let raw: Proposal;
  try {
    raw = JSON.parse(fs.readFileSync(proposalPath, "utf8")) as Proposal;
  } catch (e) {
    throw new Error("could not parse proposal payload: " + (e as Error).message);
  }
  const text = readSourceText(srcPath);
  const result = applyProposalText(text, raw);
  if (result.changed.length === 0 && result.inserted.length === 0) {
    return { changed: [], inserted: [] };
  }
  writeSourceText(srcPath, result.out);
  return { changed: result.changed, inserted: result.inserted };
}

function main(): void {
  try {
    const arg = process.argv[2];
    if (!arg) throw new Error("usage: bun scripts/apply-editor-proposal.ts <proposal.json>");
    const res = applyProposalFile(arg, SRC_PATH);
    if (res.changed.length === 0 && res.inserted.length === 0) {
      console.log("no changes needed — the data already matches");
      return;
    }
    const parts: string[] = [];
    if (res.changed.length) {
      parts.push("updated " + res.changed.length + ": " + res.changed.join(", "));
    }
    if (res.inserted.length) {
      parts.push("added " + res.inserted.length + ": " + res.inserted.join(", "));
    }
    console.log(parts.join("; "));
  } catch (e) {
    console.error("PROPOSAL REJECTED: " + (e as Error).message);
    process.exit(1);
  }
}

// Run as a CLI only when executed directly (not when imported by tests).
const IS_MAIN =
  !!process.argv[1] &&
  (import.meta.url === pathToFileURL(process.argv[1]).href ||
    process.argv[1].endsWith("apply-editor-proposal.ts"));
if (IS_MAIN) main();
