name: PR Agent

on:
  pull_request:
    types: [opened, synchronize]
  issue_comment:
    types: [created]

permissions:
  issues: write
  pull-requests: write
  contents: read

jobs:
  pr_agent_job:
    runs-on: ubuntu-latest
    if: github.event.sender.type != 'Bot'
    steps:
      - name: PR Agent action step
        id: pragent
        uses: The-PR-Agent/pr-agent@743f52d80f3513193dfc7626f778c73478df6d0a
        env:
          GOOGLE_AI_STUDIO.GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
          GITHUB_TOKEN: ${{ github.token }}
